### PR TITLE
added intx

### PR DESCRIPTION
**Pull request by cmdocmd**

### CODE REVIEW

**Comment by cmdocmd** [comment]
@Alexander9673 check this

**Comment by Alexander9673** [comment]
May i request changes? inxt is for unsigned ints, so i suggest changing the types to `u64` then the `self.data.put_int_le(int, 4);` to `self.data.put_uint_le(int, 4);`

**Comment by cmdocmd** [comment]
done

**Comment by Alexander9673** [comment]
you forgot the `int: i64` change it to `int: u64`, Also may i know your discord?

**Comment by cmdocmd** [comment]
i did u64 already my discord is cmd#4804

**Pull request merged**
